# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Method')),
                ('headers', models.TextField(blank=True, null=True, verbose_name='Headers')),
                ('remote_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remote Address')),
                ('host', models.CharField(blank=True, max_length=255, null=True, verbose_name='Host')),
                ('http_referer', models.CharField(blank=True, max_length=255, null=True, verbose_name='HTTP Referer')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Path')),
                ('query_strings', models.TextField(blank=True, null=True, verbose_name='Query Strings')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Body')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='Response Code')),
                ('form_data', models.TextField(blank=True, null=True, verbose_name='Form Data')),
                ('cookies', models.TextField(blank=True, null=True, verbose_name='Cookies')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='bucket.Bucket')),
            ],
        ),
    ]
