# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 10:39
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='custom_values',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True, verbose_name='Custom Values'),
        ),
    ]
